services:
  presenter:
    build: .
    container_name: presenter
    restart: unless-stopped
    ports:
      - "1000:1000"
    environment:
      - PORT=1000
      - NODE_ENV=production
    volumes:
      - ./db:/app/db
